export const competitions = [
    { name: 'italy-cup', id: 'CIT' },
    { name: 'johan-cruijff-schaal', id: 'NLSC' },
    { name: 'kypello-elladas', id: 'GRP' },
    { name: 'supertaca-candido-de-oliveira', id: 'POSU' },
    { name: 'russian-super-cup', id: 'RUSS' },
    { name: 'supercopa', id: 'SUC' },
    { name: 'uefa-super-cup', id: 'USC' },
    { name: 'superligaen', id: 'DK1' },
    { name: 'europa-league', id: 'EL' },
    { name: 'laliga', id: 'ES1' },
    { name: 'ligue-1', id: 'FR1' },
    { name: 'serie-a', id: 'IT1' },
    { name: 'eredivisie', id: 'NL1' },
    { name: 'russian-cup', id: 'RUP' },
    { name: 'liga-portugal-bwin', id: 'PO1' },
    { name: 'belgian-supercup', id: 'BESC' },
    { name: 'premier-league', id: 'GB1' },
    { name: 'europa-league-qualifikation', id: 'ELQ' },
    { name: 'efl-cup', id: 'CGB' },
    { name: 'sydbank-pokalen', id: 'DKP' },
    { name: 'uefa-europa-conference-league-qualifikation', id: 'ECLQ' },
    { name: 'fa-cup', id: 'FAC' },
    { name: 'toto-knvb-beker', id: 'NLP' },
    { name: 'ukrainian-super-cup', id: 'UKRS' },
    { name: 'premier-liga', id: 'UKR1' },
    { name: 'copa-del-rey', id: 'CDR' },
    { name: 'uefa-champions-league', id: 'CL' },
    { name: 'super-league-1', id: 'GR1' },
    { name: 'super-lig', id: 'TR1' },
    { name: 'allianz-cup', id: 'POCP' },
    { name: 'community-shield', id: 'GBCS' },
    { name: 'fifa-klub-wm', id: 'KLUB' },
    { name: 'bundesliga', id: 'L1' },
    { name: 'premier-liga', id: 'RU1' },
    { name: 'scottish-premiership', id: 'SC1' },
    { name: 'supercoppa-italiana', id: 'SCI' },
    { name: 'jupiler-pro-league', id: 'BE1' },
    { name: 'uefa-champions-league-qualifikation', id: 'CLQ' },
    { name: 'dfl-supercup', id: 'DFL' },
    { name: 'sfa-cup', id: 'SFA' },
    { name: 'ukrainian-cup', id: 'UKRP' },
    { name: 'dfb-pokal', id: 'DFB' },
    { name: 'trophee-des-champions', id: 'FRCH' }
];

export const competitionsFormatted = [
    { name: 'Superligaen', id: 'DK1' },
    { name: 'Laliga', id: 'ES1' },
    { name: 'Ligue 1', id: 'FR1' },
    { name: 'Serie A', id: 'IT1' },
    { name: 'Eredivisie', id: 'NL1' },
    { name: 'Liga Portugal Bwin', id: 'PO1' },
    { name: 'Premier League', id: 'GB1' },
    { name: 'Premier Liga', id: 'UKR1' },
    { name: 'Super League 1', id: 'GR1' },
    { name: 'Super Lig', id: 'TR1' },
    { name: 'Bundesliga', id: 'L1' },
    { name: 'Premier Liga', id: 'RU1' },
    { name: 'Scottish Premiership', id: 'SC1' },
    { name: 'Jupiler Pro League', id: 'BE1' },
];
