const competitions = [
    { name: 'Italy Cup', id: 'CIT', type: 'domestic_cup' },
    { name: 'Johan Cruijff Schaal', id: 'NLSC', type: 'other' },
    { name: 'Kypello Elladas', id: 'GRP', type: 'domestic_cup' },
    { name: 'Supertaca Candido De Oliveira', id: 'POSU', type: 'other' },
    { name: 'Russian Super Cup', id: 'RUSS', type: 'other' },
    { name: 'Super Copa', id: 'SUC', type: 'other' },
    { name: 'UEFA Super Cup', id: 'USC', type: 'other' },
    { name: 'Superligaen', id: 'DK1', type: 'domestic_league' },
    { name: 'UEFA Europa League', id: 'EL', type: 'international_cup' },
    { name: 'La Liga', id: 'ES1', type: 'domestic_league' },
    { name: 'Ligue 1', id: 'FR1', type: 'domestic_league' },
    { name: 'Serie A', id: 'IT1', type: 'domestic_league' },
    { name: 'Eredivisie', id: 'NL1', type: 'domestic_league' },
    { name: 'Russian Cup', id: 'RUP', type: 'domestic_cup' },
    { name: 'Liga Portugal Bwin', id: 'PO1', type: 'domestic_league' },
    { name: 'Belgian Super Cup', id: 'BESC', type: 'other' },
    { name: 'Premier League', id: 'GB1', type: 'domestic_league' },
    { name: 'UEFA Europa League Qualifying', id: 'ELQ', type: 'international_cup' },
    { name: 'EFL Cup', id: 'CGB', type: 'other' },
    { name: 'Sydbank Pokalen', id: 'DKP', type: 'domestic_cup' },
    { name: 'UEFA Europa Conference League Qualifying', id: 'ECLQ', type: 'international_cup' },
    { name: 'FA Cup', id: 'FAC', type: 'domestic_cup' },
    { name: 'Toto KNVB Beker', id: 'NLP', type: 'domestic_cup' },
    { name: 'Ukrainian Super Cup', id: 'UKRS', type: 'other' },
    { name: 'Ukrainian Premier Liga', id: 'UKR1', type: 'domestic_league' },
    { name: 'Copa Del Rey', id: 'CDR', type: 'domestic_cup' },
    { name: 'UEFA Champions League', id: 'CL', type: 'international_cup' },
    { name: 'Super League 1', id: 'GR1', type: 'domestic_league' },
    { name: 'Super Lig', id: 'TR1', type: 'domestic_league' },
    { name: 'Allianz Cup', id: 'POCP', type: 'domestic_cup' },
    { name: 'Community Shield', id: 'GBCS', type: 'other' },
    { name: 'FIFA Club World Cup', id: 'KLUB', type: 'other' },
    { name: 'Bundesliga', id: 'L1', type: 'domestic_league' },
    { name: 'Scottish Premiership', id: 'SC1', type: 'domestic_league' },
    { name: 'Supercoppa Italiana', id: 'SCI', type: 'other' },
    { name: 'Jupiler Pro League', id: 'BE1', type: 'domestic_league' },
    { name: 'UEFA Champions League Qualifying', id: 'CLQ', type: 'international_cup' },
    { name: 'DFL Supercup', id: 'DFL', type: 'other' },
    { name: 'SFA Cup', id: 'SFA', type: 'domestic_cup' },
    { name: 'Ukrainian Cup', id: 'UKRP', type: 'domestic_cup' },
    { name: 'DFB Pokal', id: 'DFB', type: 'domestic_cup' },
    { name: 'Trophee des Champions', id: 'FRCH', type: 'other' }
];
const year = [
    {name: '2012'}, 
    {name: '2013'}, 
    {name: '2014'},
    {name: '2015'}, 
    {name: '2016'}, 
    {name: '2017'}, 
    {name: '2018'}, 
    {name: '2019'}, 
    {name: '2020'}, 
    {name: '2021'}, 
    {name: '2022'}, 
    {name: '2023'}
]
const round_domestic_league = [
    {name: '1. Matchday'}, 
    {name: '2. Matchday'}, 
    {name: '3. Matchday'}, 
    {name: '4. Matchday'}, 
    {name: '5. Matchday'}, 
    {name: '6. Matchday'}, 
    {name: '7. Matchday'}, 
    {name: '8. Matchday'}, 
    {name: '9. Matchday'}, 
    {name: '10. Matchday'}, 
    {name: '11. Matchday'}, 
    {name: '12. Matchday'}, 
    {name: '13. Matchday'}, 
    {name: '14. Matchday'}, 
    {name: '15. Matchday'}, 
    {name: '16. Matchday'}, 
    {name: '17. Matchday'}, 
    {name: '18. Matchday'}, 
    {name: '19. Matchday'}, 
    {name: '20. Matchday'}, 
    {name: '21. Matchday'}, 
    {name: '22. Matchday'}, 
    {name: '23. Matchday'}, 
    {name: '24. Matchday'}, 
    {name: '25. Matchday'}, 
    {name: '26. Matchday'}, 
    {name: '27. Matchday'}, 
    {name: '28. Matchday'}, 
    {name: '29. Matchday'}, 
    {name: '30. Matchday'}, 
    {name: '31. Matchday'}, 
    {name: '32. Matchday'}, 
    {name: '33. Matchday'}, 
    {name: '34. Matchday'}, 
    {name: '35. Matchday'}, 
    {name: '36. Matchday'}, 
    {name: '37. Matchday'}, 
    {name: '38. Matchday'}, 
    {name: '39. Matchday'},
    {name: '40. Matchday'},
    {name: '41. Matchday'},
    {name: '42. Matchday'},
]

const round_domestic_cup = [
    {name: '3rd round 1st leg'},
    {name: '3rd round 2nd leg'},
    {name: '4th round 1st leg'},
    {name: '4th round 2nd leg'},
    {name: '4th round deciders'},
    {name: '5th round 1st leg'},
    {name: '5th round 2nd leg'},
    {name: '5th round deciders'},
    {name: '6th round deciders'},
    {name: 'Fitfh Round'},
    {name: 'Final'},
    {name: 'First Preliminary Round'},
    {name: 'First Round'},
    {name: 'First Round 1st leg'},
    {name: 'First Round 2nd leg'},
    {name: 'First Round Replay'},
    {name: 'Fourth Round'},
    {name: 'Group 1'},
    {name: 'Group 10'},
    {name: 'Group 11'},
    {name: 'Group 2'},
    {name: 'Group 3'},
    {name: 'Group 4'},
    {name: 'Group 5'},
    {name: 'Group 6'},
    {name: 'Group 7'},
    {name: 'Group 8'},
    {name: 'Group A'},
    {name: 'Group B'},
    {name: 'Group C'},
    {name: 'Group D'},
    {name: 'Group E'},
    {name: 'Group F'},
    {name: 'Group G'}, 
    {name: 'Group H'}, 
    { name: 'Qualifying Round' },
    { name: 'Quarter-Finals' },
    { name: 'Quarter-Finals 1st leg' },
    { name: 'Quarter-Finals 2nd leg' },
    { name: 'Round of 16' },
    { name: 'Round of 16 Replay' },
    { name: 'Second Round' },
    { name: 'Second Round 1st leg' },
    { name: 'Second Round 2nd leg' },
    { name: 'Second Round Replay' },
    { name: 'Semi-Finals' },
    { name: 'Semi-Finals 1st Leg' },
    { name: 'Semi-Finals 2nd Leg' },
    { name: 'Sixth Round' },
    { name: 'Third Round' },
    { name: 'Third Round Replay' },
    { name: 'group 9' },
    { name: 'intermediate stage' },
    { name: 'intermediate stage 1st leg' },
    { name: 'intermediate stage 2nd leg' },
    { name: 'last 16 1st leg' },
    { name: 'last 16 2nd leg' },
    { name: 'qualification round deciders' },
    { name: 'quarter-finals deciders' },
    { name: 'semi-finals deciders' }
]

const round_international_cup = [
    { name: '3rd round 1st leg' },
    { name: '3rd round 2nd leg' },
    { name: '4th round 1st leg' },
    { name: '4th round 2nd leg' },
    { name: 'Final' },
    { name: 'First Round' },
    { name: 'First Round 1st leg' },
    { name: 'First Round 2nd leg' },
    { name: 'Group A' },
    { name: 'Group B' },
    { name: 'Group C' },
    { name: 'Group D' },
    { name: 'Group E' },
    { name: 'Group F' },
    { name: 'Group G' },
    { name: 'Group H' },
    { name: 'Qualifying Round' },
    { name: 'Qualifying Round 1st leg' },
    { name: 'Qualifying Round 2nd leg' },
    { name: 'Quarter-Finals' },
    { name: 'Quarter-Finals 1st leg' },
    { name: 'Quarter-Finals 2nd leg' },
    { name: 'Round of 16' },
    { name: 'Second Round' },
    { name: 'Second Round 1st leg' },
    { name: 'Second Round 2nd leg' },
    { name: 'Semi-Finals' },
    { name: 'Semi-Finals 1st Leg' },
    { name: 'Semi-Finals 2nd Leg' },
    { name: 'Third Round' },
    { name: 'group I' },
    { name: 'group J' },
    { name: 'group K' },
    { name: 'group L' },
    { name: 'intermediate stage' },
    { name: 'intermediate stage 1st leg' },
    { name: 'intermediate stage 2nd leg' },
    { name: 'intermediate stage deciders' },
    { name: 'last 16 1st leg' },
    { name: 'last 16 2nd leg' }
]

const round_other = [
    { name: '5th place match' },
    { name: 'Final' },
    { name: 'Final round first leg' },
    { name: 'First Round' },
    { name: 'Fourth Round' },
    { name: 'Qualifying Round' },
    { name: 'Quarter-Finals' },
    { name: 'Second Round' },
    { name: 'Semi-Finals' },
    { name: 'Third Place Play-Off' },
    { name: 'Third Round' },
    { name: 'final 1st leg' },
    { name: 'final 2nd leg' },
    { name: 'final decider' }
]

export { competitions, year, round_domestic_league, round_domestic_cup, round_international_cup, round_other};