server.port=8080
# DataSource settings: PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/football_analyzer_db
spring.datasource.username=postgres
spring.datasource.password=150402

# Specify the JDBC driver for PostgreSQL
# spring.datasource.driver-class-name= org.postgresql.Driver

# Hibernate properties
# You can configure additional Hibernate properties here if needed
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
